<?php

namespace Container3wiEqSo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J4vEpsxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J4vEpsx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J4vEpsx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CountryController::delete' => ['privates', '.service_locator.u2JReeV', 'get_ServiceLocator_U2JReeVService', true],
            'App\\Controller\\CountryController::edit' => ['privates', '.service_locator.u2JReeV', 'get_ServiceLocator_U2JReeVService', true],
            'App\\Controller\\CountryController::index' => ['privates', '.service_locator.1rC5dQh', 'get_ServiceLocator_1rC5dQhService', true],
            'App\\Controller\\CountryController::show' => ['privates', '.service_locator.u2JReeV', 'get_ServiceLocator_U2JReeVService', true],
            'App\\Controller\\InicioController::index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\PersonController::delete' => ['privates', '.service_locator.pHY_vS7', 'get_ServiceLocator_PHYVS7Service', true],
            'App\\Controller\\PersonController::edit' => ['privates', '.service_locator.pHY_vS7', 'get_ServiceLocator_PHYVS7Service', true],
            'App\\Controller\\PersonController::index' => ['privates', '.service_locator.MlR0_Bg', 'get_ServiceLocator_MlR0BgService', true],
            'App\\Controller\\PersonController::show' => ['privates', '.service_locator.pHY_vS7', 'get_ServiceLocator_PHYVS7Service', true],
            'App\\Controller\\PostController::delete' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CountryController:delete' => ['privates', '.service_locator.u2JReeV', 'get_ServiceLocator_U2JReeVService', true],
            'App\\Controller\\CountryController:edit' => ['privates', '.service_locator.u2JReeV', 'get_ServiceLocator_U2JReeVService', true],
            'App\\Controller\\CountryController:index' => ['privates', '.service_locator.1rC5dQh', 'get_ServiceLocator_1rC5dQhService', true],
            'App\\Controller\\CountryController:show' => ['privates', '.service_locator.u2JReeV', 'get_ServiceLocator_U2JReeVService', true],
            'App\\Controller\\InicioController:index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\PersonController:delete' => ['privates', '.service_locator.pHY_vS7', 'get_ServiceLocator_PHYVS7Service', true],
            'App\\Controller\\PersonController:edit' => ['privates', '.service_locator.pHY_vS7', 'get_ServiceLocator_PHYVS7Service', true],
            'App\\Controller\\PersonController:index' => ['privates', '.service_locator.MlR0_Bg', 'get_ServiceLocator_MlR0BgService', true],
            'App\\Controller\\PersonController:show' => ['privates', '.service_locator.pHY_vS7', 'get_ServiceLocator_PHYVS7Service', true],
            'App\\Controller\\PostController:delete' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CountryController::delete' => '?',
            'App\\Controller\\CountryController::edit' => '?',
            'App\\Controller\\CountryController::index' => '?',
            'App\\Controller\\CountryController::show' => '?',
            'App\\Controller\\InicioController::index' => '?',
            'App\\Controller\\PersonController::delete' => '?',
            'App\\Controller\\PersonController::edit' => '?',
            'App\\Controller\\PersonController::index' => '?',
            'App\\Controller\\PersonController::show' => '?',
            'App\\Controller\\PostController::delete' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CountryController:delete' => '?',
            'App\\Controller\\CountryController:edit' => '?',
            'App\\Controller\\CountryController:index' => '?',
            'App\\Controller\\CountryController:show' => '?',
            'App\\Controller\\InicioController:index' => '?',
            'App\\Controller\\PersonController:delete' => '?',
            'App\\Controller\\PersonController:edit' => '?',
            'App\\Controller\\PersonController:index' => '?',
            'App\\Controller\\PersonController:show' => '?',
            'App\\Controller\\PostController:delete' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
