<?php

namespace Container3wiEqSo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pHY_vS7.App\Entity\Person' shared service.
     *
     * @return \App\Entity\Person
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pHY_vS7": it references class "App\\Entity\\Person" but no such service exists.');
    }
}
