<?php

namespace Container9uUSJdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2JReeVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u2JReeV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u2JReeV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'country' => ['privates', '.errored..service_locator.u2JReeV.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.u2JReeV": it references class "App\\Entity\\Country" but no such service exists.'],
        ], [
            'country' => 'App\\Entity\\Country',
        ]);
    }
}
